#! /bin/bash

#the script will search for the  text passed as argument inside
#all pdf files recursively in the current directory
# usage ./searchPdf text_to_search

find . -name '*.pdf' -exec pdfgrep -n -i $1 {} +
